### PR TITLE
[pylint] Add more path to sys.path in .pylintrc

### PR DESCRIPTION
**Pull request by csordasmarton**
Add `web`, `web/client` and `web/server` directories to the `sys.path` in the `.pylintrc` file.

### CODE REVIEW

**Comment by bruntib** [comment]
What is the use of adding these paths to the `sys.path`?

**Comment by csordasmarton** [comment]
@bruntib `Pylint` will be unable to import modules from these directories. E.g.:
```py
from codechecker_web.shared import database_status  # Error: Unable to import codechecker_web.shared
```
So it will give you a warning message if you run it for example through VSCode.

**Comment by bruntib** [comment]
But why are these special? Because the 3rd parties, like thrift libs and plist_to_html are understandable. But why don't we have to list all CodeChecker modules then?

**Comment by csordasmarton** [comment]
@bruntib During the repository split up (https://github.com/Ericsson/codechecker/issues/1830) as we discussed with @gyorb we created the following main modules:
- `codechecker_common`
- `codechecker_analyzer`
- `codechecker_web`
- `codechecker_client`
- `codechecker_server`

If you would like to import something from these modules you will use the following format:
`<main_module_name>.<module_name>`.

E.g.:
```py
from codechecker_analyzer.buildlog import log_parser
```

One more important thing that for example `codechecker_analyzer` and `codechecker_client` both contain a package called `cmd`. This way we cannot list these modules in this file because the `cmd` package will not be unique.

**Pull request merged**
