### PR TITLE
Show number of bugs by severity

### PR DESCRIPTION
**Pull request by bruntib**
This commit may be related to #361.

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Isn't it a performance bottleneck to do this query on the client side instead of making the server to send this data to the client? In case this is cheap, LGTM!

**Comment by bruntib** [comment]
The computation goes on server side by calling `getRunResultCount()` API function, in addition it is called asynchronously. I'm rather worried about server side, because this tends to be a slow function. I haven't tested it on a big database, but for the same reason is the "checker id" filter field asynchronous. I think it would even be worth to store these sums in the database or at least in a server-side cache as these are queried all the time when the GUI page is loaded.

**Comment by gyorb** [comment]
The server side cache for the summaries is a nice idea.

**Comment by Xazax-hun** [comment]
Is the cache ever cleared? Is this a good idea? 
Maybe a new API to query this info efficiently would be better.

**Comment by Xazax-hun** [comment]
I think we should not introduce caching but a new API call for now for the following results:
* What is the cache invalidation logic? And currently the cache can only grow, it is a leak. It can be a problem on long running CI servers eventually.
* Should we protect the cache with a lock? Interprocess or interthread lock? 
* Should we introduce separate caching mechanisms for all of the features?

Using a new API call we do not need to solve those problems and can be still performant.

**Comment by Xazax-hun** [comment]
This will be subsumed by the new filtering GUI.

**Pull request closed without merging**
