### PR TITLE
[clang] Upgrade to Clang11

### PR DESCRIPTION
**Pull request by bruntib**

### CODE REVIEW

**Review by gyorb — CHANGES_REQUESTED** [review]
Please update the clang version checking script for the tests so the minimal required clang and clang-tidy versions are 11.
https://github.com/Ericsson/codechecker/blob/master/scripts/test/check_clang.py

**Comment by dkrupp** [comment]
LGTM

**Review by dkrupp — COMMENTED** [review]
LGTM

**Review by dkrupp — APPROVED** [review]
LGTM

**Pull request merged**
