### PR TITLE
[gui] Show selected filter items at Review status filter

### PR DESCRIPTION
**Pull request by csordasmarton**

### CODE REVIEW

**Comment by bruntib** [comment]
What does this patch change? I can't see any difference in the GUI.

**Comment by csordasmarton** [comment]
This patch will show the selected review status filter items after the Review status filter label. Similarly to the Detection status filter.
image

**Comment by bruntib** [comment]
For some reason it doesn't work for me. Sometimes three dots "..." appear after "Latest Review Status", but I can't see the selected labels :confused:

**Comment by csordasmarton** [comment]
@bruntib Maybe the size of the sidebar is too small. Try to increase it and instead of the three dots I think you will see the selected items.

**Review by gyorb — CHANGES_REQUESTED** [review]
I see only the three dots, even resizing the sidebar did not help.
Tested in Firefox 81.0 and Chromium 85.0.4183.121.

It does not change even if I change the filter values and apply them.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6174498&bid=20156949)

**Review by gyorb — APPROVED** [review]

**Pull request merged**
