### PR TITLE
[report-converter][cmd] Add smatch parser

### PR DESCRIPTION
**Pull request by sudipm-mukherjee**
Add support to parse output from smatch and use in report converter tool.
Smatch is a static analysis tool mostly used for the kernel source.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tools/report-converter/codechecker_report_converter/smatch/analyzer_result.py  2
- tools/report-converter/codechecker_report_converter/smatch/output_parser.py  3
         

Clones added
============
- tools/report-converter/codechecker_report_converter/smatch/output_parser.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6318358&bid=20539473)

**Comment by sudipm-mukherjee** [comment]
> Codacy Here is an overview of what got changed by this pull request:
> 
> ```diff
> Complexity increasing per file
> ==============================
> - tools/report-converter/codechecker_report_converter/smatch/analyzer_result.py  2
> - tools/report-converter/codechecker_report_converter/smatch/output_parser.py  3
>          
> 
> Clones added
> ============
> - tools/report-converter/codechecker_report_converter/smatch/output_parser.py  2
>          
> ```
> 
> See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6318358&bid=20539473)

@gyorb sorry, I have no idea what you meant by that. :(

**Comment by bulwahn** [comment]
@sudipm-mukherjee Jay is working on the same here: https://github.com/Ericsson/codechecker/pull/2968

so, I suggest we close this pull request and wait until the other is merged.

**Comment by gyorb** [comment]
@sudipm-mukherjee Codacy is a tool which runs some python and javascript linters on the changed source code and for some reason it comments in my name (probably because I've connected it with the github repo). So this is an automatic comment about the change.

I will close this PR as @bulwahn mentioned because this is a duplicate. Feel free to reopen or update it if this will be still required after the other PR was merged.

**Comment by sudipm-mukherjee** [comment]
> @sudipm-mukherjee Codacy is a tool which runs some python and javascript linters on the changed source code and for some reason it comments in my name (probably because I've connected it with the github repo). So this is an automatic comment about the change.
> 
> I will close this PR as @bulwahn mentioned because this is a duplicate. Feel free to reopen or update it if this will be still required after the other PR was merged.

Thats ok. Thanks @gyorb. I did not know that smatch support was planned. I needed smatch support for a CI pipeline I was working on and so modified the coccinelle implementation to parse smatch report.                      
And just fyi, you can see the pipeline at https://travis-ci.org/github/sudipm-mukherjee/linux-test/jobs/735322211 and the generated reports at https://sudipm-mukherjee.github.io/

**Comment by gyorb** [comment]
@sudipm-mukherjee thanks for showing the CI pipeline great job!
How did you integrate CodeChecker (or only the report converters) into the travis CI job? Are they cloned and installed from the CodeChecker repository during the travis build?

If you have multiple thousand reports probably it is worth storing them into the CodeChecker webserver with a database to manage the reports. It depends on your CI requirements but after some time managing a lot of html reports can be problematic.

**Comment by sudipm-mukherjee** [comment]
@gyorb 

> @sudipm-mukherjee thanks for showing the CI pipeline great job!
> How did you integrate CodeChecker (or only the report converters) into the travis CI job? Are they cloned and installed from the CodeChecker repository during the travis build?

No, they are in a docker image. Each stage is pulling separate docker images based on what test it is supposed to run or if its the report generator stage.

> 
> If you have multiple thousand reports probably it is worth storing them into the CodeChecker webserver with a database to manage the reports. It depends on your CI requirements but after some time managing a lot of html reports can be problematic.

Yes, but since many others will need to look at those reports so having them locally will not work. But, I think in due course we will need to plan for a server or vm to serve the pages from CodeChecker webserver .

**Pull request closed without merging**
