### PR TITLE
Show bug path length for a report

### LINKED ISSUE #1505: Show bug path length for a report in bug report selection (left-hand, dropdown)
In the file's bug list: image

And in the "also found" drop-down: 
image
This latter one, as seen in the picture, doesn't feel too user-friendly.

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #1505

Show bug path length for a report in bug report selection at bug tree and same report selector.

Screenshots:
cc_bug_path_len1

cc_bug_path_len2

### CODE REVIEW

**Comment by gyorb** [comment]
Do we want to use the same path number coloring here? I think they can be a bit distracting here.
What do you think if we would just show the numbers here?

**Comment by csordasmarton** [comment]
@gyorb  Done.

I have also created a tooltip on the nodes at bug tree to show the details of the report:

cc_report_details

**Comment by whisperity** [comment]
@csordasmarton I have one more comment not entirely related to the current patch but could be added with this. Are we sorting defects that are reported to the exact same line based on BPL? If not, I think this could be a useful addition... if there are multiple bugs *from the same checker* reported *to the same line*, the shortest one should be first in the left-hand list.

I know when clicking in the bug list we jump to the shortest one.

**Comment by gyorb** [comment]
@whisperity I think the current ordering is based on the line in the source file where the bug was reported, do we really want to change this to sort based on the bug path length?

**Comment by csordasmarton** [comment]
@whisperity I did it in this pull request but in a separate commit.

**Pull request merged**
