### PR TITLE
enable cyclic-import and consider-iterating-dictionary checks

### LINKED ISSUE #2084: fix pylint consider-iterating-dictionary warning
C0201 - Consider iterating the dictionary directly instead of calling .keys()
It is enough to just iterate through the dictionary like:
`for key in dictionary`

### LINKED ISSUE #2904: enable cyclic-import check in pylint
enable cyclic-import check in pylint and fix the imports if there are problems

### PR DESCRIPTION
**Pull request by zukatsinadze**
Close #2904 
Close #2084

Just enabled checks, no issues found.

### CODE REVIEW

**Review by csordasmarton — CHANGES_REQUESTED** [review]
We have a couple of more .pylintrc configuration files for tools:
- https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/analyzer/tools/statistics_collector/.pylintrc#L62
- https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/analyzer/tools/merge_clang_extdef_mappings/.pylintrc#L62
- https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/codechecker_report_hash/.pylintrc#L62
- https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/report-converter/.pylintrc#L62
- https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/tu_collector/.pylintrc#L62

@zukatsinadze Could you please enable these rules in these files too?

**Comment by zukatsinadze** [comment]
> 
> 
> We have a couple of more .pylintrc configuration files for tools:
> 
>     * https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/analyzer/tools/statistics_collector/.pylintrc#L62
> 
>     * https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/analyzer/tools/merge_clang_extdef_mappings/.pylintrc#L62
> 
>     * https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/codechecker_report_hash/.pylintrc#L62
> 
>     * https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/report-converter/.pylintrc#L62
> 
>     * https://github.com/Ericsson/codechecker/blob/d05b8a73f8c00498186153378f5663f883a74f5a/tools/tu_collector/.pylintrc#L62
> 
> 
> @zukatsinadze Could you please enable these rules in these files too?

Done

**Comment by csordasmarton** [comment]
@zukatsinadze could you please rebase your PR because the CI (github action) contained a bug and the test cases are failing. On the master branch now it is fixed with #3317.

**Comment by zukatsinadze** [comment]
> 
> 
> @zukatsinadze could you please rebase your PR because the CI (github action) contained a bug and the test cases are failing. On the master branch now it is fixed with #3317.

@csordasmarton rebased.

**Review by csordasmarton — APPROVED** [review]
LGTM! Thank you for this patch and the quick fixes.

**Pull request merged**
