### PR TITLE
Fix `checkers --warnings` command

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Review by gyorb — COMMENTED** [review]
Hi,

pylint found some warning in travis, could you fix it?
```
codechecker_analyzer/cmd/checkers.py:386:55: E711 comparison to None should be 'if cond is not None:'
```

**Comment by jimis** [comment]
> Hi,
> 
> pylint found some warning in travis, could you fix it?
> 
> ```
> codechecker_analyzer/cmd/checkers.py:386:55: E711 comparison to None should be 'if cond is not None:'
> ```

Done, and also removed the `if 'guideline' in args' part, according to other parts in the same file.

**Comment by jimis** [comment]
@gyorb is something left to do on my part?

**Comment by gyorb** [comment]
@jimis it would be great if you could add a simple test. There is already a simple test which checks if the checkers subcommand can be executed successfully [here](https://github.com/Ericsson/codechecker/blob/master/analyzer/tests/functional/cmdline/test_cmdline.py#L87)

I think a test case like that for this case would be great with one addition to check if the output contains the at least one `clang-diagnostic-...` value, which are the warnings.

**Comment by jimis** [comment]
OK @gyorb. I can assert that "clang-diagnostic-vla" is included in the output, for example.

But I'm not sure yet that the output is correct. There is an empty entry "clang-diagnostic-" which comes from the generic "-W" flag that includes all warnings. There is another entry "clang-diagnostic-extra" that comes from "-Wextra". Are these supposed to be meta-checkers "containing" other checkers? Anyway their presence seems harmless so I just ignore these lines ATM.

**Comment by jimis** [comment]
I don't have correct environment to run the test, so lets see how it goes in Travis.

**Comment by jimis** [comment]
In Travis I see the message:
```
************* Module codechecker_client.cmd_line_client
[E1136] client/codechecker_client/cmd_line_client.py:103:27: Value 'Union' is unsubscriptable
```

I don't think my test got executed. It looks like pylint incorrectly reports this with python-3.9: https://github.com/qemu/qemu/commit/eeb7314c46545a2426c39e2c00f03a0ab5f4f4f1

I'll submit a commit that disables the warning.

**Comment by gyorb** [comment]
Thanks for checking the pylint warning! It was only produced in the osx test environment probably because there was a newer python version. That commit should resolve #2997 what do you think @csordasmarton?

**Comment by jimis** [comment]
Now it seems Travis is running a different set of jobs! And they failed again. I'm not sure I can see my test running anywhere and I don't make much sense of what's going on, so please let me know @gyorb if I should change anything. Thanks!

**Comment by csordasmarton** [comment]
@jimis Could you please rebase and force push your commits? There was a pull requests which changed the clang version inside the travis jobs (#2993) and I think your failure is related to this (Unable to locate package clang-11). I also removed all the caches from travis jobs.

**Comment by jimis** [comment]
Thanks @csordasmarton,  lets see if tests pass now.

**Review by gyorb — APPROVED** [review]

**Comment by gyorb** [comment]
Thank you for the fix @jimis

**Pull request merged**
