### PR TITLE
[gui] Rename Newcheck to Compare to for better understandability

### PR DESCRIPTION
**Pull request by csordasmarton**

### CODE REVIEW

**Comment by csordasmarton** [comment]
@bruntib I renamed some files and some other newcheck words but the source code still contains some of it related to url parameters.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5929041&bid=19427187)

**Comment by gyorb** [comment]
so in this case the filter in the url will contain the base and newcheck naming to keep the backward compatibility, otherwise the compare-to new naming is used?

**Comment by csordasmarton** [comment]
@gyorb No, only the newcheck name is used in the url. The url name is not changed.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5929041&bid=19427187)

**Pull request merged**
