### PR TITLE
Updated OSX support

### PR DESCRIPTION
**Pull request by gyorb**
This is an updated version for the latest codechecker of the original OSX support pull request #315 created by @tmsblgh.
Thanks your work!

### CODE REVIEW

**Comment by r0mai** [comment]
Continuing the discussion here:

I tried compiling vim with CodeCheker. Here is what I did:

* cloned vim
* `$ CodeChecker check -n test_project_check_vim -b "make"`

Output:

```
[...normal build output from vim...]
[INFO] - Build finished successfully.
[INFO] - Waiting for check results on [62474]
[INFO] - Static analysis is starting ...
[ERROR] - Analyzing charset.c failed.
[ERROR] - In file included from /Users/r0mai/workspace/vim/src/charset.c:10:
In file included from /Users/r0mai/workspace/vim/src/vim.h:2114:
/Users/r0mai/workspace/vim/src/proto.h:39:12: fatal error: 'os_unix.pro' file not found
#  include "os_unix.pro"
           ^
1 error generated.

[ERROR] - Analyzing memline.c failed.
[ERROR] - In file included from /Users/r0mai/workspace/vim/src/memline.c:45:
In file included from /Users/r0mai/workspace/vim/src/vim.h:2114:
/Users/r0mai/workspace/vim/src/proto.h:39:12: fatal error: 'os_unix.pro' file not found
#  include "os_unix.pro"
           ^
1 error generated.

[ERROR] - Analyzing buffer.c failed.
[ERROR] - In file included from /Users/r0mai/workspace/vim/src/buffer.c:28:
In file included from /Users/r0mai/workspace/vim/src/vim.h:2114:
/Users/r0mai/workspace/vim/src/proto.h:39:12: fatal error: 'os_unix.pro' file not found
#  include "os_unix.pro"
           ^
1 error generated.

[ERROR] - Analyzing evalfunc.c failed.
[ERROR] - In file included from /Users/r0mai/workspace/vim/src/evalfunc.c:15:
In file included from /Users/r0mai/workspace/vim/src/vim.h:2114:
/Users/r0mai/workspace/vim/src/proto.h:39:12: fatal error: 'os_unix.pro' file not found
#  include "os_unix.pro"
           ^
1 error generated.

[ERROR] - Analyzing window.c failed.
[ERROR] - In file included from /Users/r0mai/workspace/vim/src/window.c:10:
In file included from /Users/r0mai/workspace/vim/src/vim.h:2114:
/Users/r0mai/workspace/vim/src/proto.h:39:12: fatal error: 'os_unix.pro' file not found
#  include "os_unix.pro"
           ^
1 error generated.

[ERROR] - Analyzing spell.c failed.
[... lot more of these ...]

Traceback (most recent call last):
  File "/Users/r0mai/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_lib/analysis_manager.py", line 121, in check
    rh.handle_results()
  File "/Users/r0mai/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_lib/analyzers/result_handler_plist_to_db.py", line 57, in handle_results
    source_file_name)
  File "/Users/r0mai/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_lib/client.py", line 162, in add_build_action
    analyzed_source_file)
  File "/Users/r0mai/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 320, in addBuildAction
    return self.recv_addBuildAction()
  File "/Users/r0mai/codechecker_package/CodeChecker/cc_lib/python2.7/codechecker_gen/DBThriftAPI/CheckerReport.py", line 348, in recv_addBuildAction
    raise result.requestError
RequestFailed: RequestFailed(_message="(sqlite3.OperationalError) no such column: build_actions.analyzer_type [SQL: u'SELECT build_actions.id AS build_actions_id, build_actions.run_id AS build_actions_run_id, build_actions.build_cmd AS build_actions_build_cmd, build_actions.analyzer_type AS build_actions_analyzer_type, build_actions.analyzed_source_file AS build_actions_analyzed_source_file, build_actions.check_cmd AS build_actions_check_cmd, build_actions.failure_txt AS build_actions_failure_txt, build_actions.date AS build_actions_date, build_actions.duration AS build_actions_duration \\nFROM build_actions \\nWHERE build_actions.run_id = ? AND build_actions.build_cmd = ? AND (build_actions.analyzer_type = ? AND build_actions.analyzed_source_file = ? OR build_actions.analyzer_type = ? AND build_actions.analyzed_source_file = ?)'] [parameters: (3, 'cc -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X_UNIX -O2 -fno-strength-reduce -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -o objects/dict.o dict.c', 'clang-tidy', 'dict.c', u'', u'')]", error_code=0)
[... lot more of these too ...]

[INFO] - ----==== Summary ====----
[INFO] - Total compilation commands: 126
[INFO] - Failed to analyze
[INFO] -   clangsa: 63
[INFO] -   clang-tidy: 63
[INFO] - ----=================----
[INFO] - Analysis length: 19.4336190224 sec.
[INFO] - Analysis has finished.
[INFO] - To view results run:
CodeChecker server -w /Users/r0mai/.codechecker
```

The check result tab appeared in the webpage, but with no results.

I suspect the problem is that the compilation used the system compiler (xcode's Apple LLVm), but the analyser tried to use the custom built and locally installed clang. Apparently the locally built and installed clang couldn't compile it? 

More clarification about this in the readme would be helpful. As you may know, on OS X, replacing the system compiler is not trivial and generally not advised, because things can stop working. That's why I installed it locally.

How does code checker work? How does it replace or trace the compilation process? Can it work based on a `compile_commands.json`?

**Comment by gyorb** [comment]
The database errors are because automatic schema upgrade is not supported for SQLite, you should delete the previous codechecker workspace (the schema was changed).

I asume building vim without checking it is successful.
Codechecker uses clang/clang-tidy found in the ```PATH```by default. [Extra compiler options](https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#forward-compiler-options) can be forwarded if needed for the analysis.
Are you sure that different clang versions are used for the original build and for the analysis?

You can try to generate the ```compile_commands.json``` file with ```intercept-build``` and use generated json for the analysis.
CodeChecker can work with an available ```compile_commands.json``` (generated by CMake or intercept-build), you can use the ```-l``` option instead of ```-b``` in the command line.

**Comment by tmsblgh** [comment]
Currently I am on macOS Sierra and now I can not build vim... Tomorrow I will try to downgrade to El Capitan and try to reproduce which you wrote.

On OS X the CodeChecker trying to use scan-build-py to make compile_commands.json, the original LD_PRELOAD technique was Linux specific.

Yes, you can check with CodeChecker based on a json file. Try something like these: `CodeChecker check -n test_based_on_json -j compile_commands.json`

**Comment by r0mai** [comment]
Ok, the database clear did the trick. I have some results now:

screen shot 2016-08-29 at 23 13 34

I'm trying a bigger project now which is cmake based so it has compile_commands.json trivially. So far it's running but fails to compile basically every file due to missing includes (these are project headers, not system headers). The `-I` paths in the compilation database are relative to the `directory` entry. I think CodeChecker doesn't take this into account, because when I ran it from the build directory (where cmake was ran) it did more.

Then it started to not find STL headers. I could fix this by generating compile_commands.json with the same custom compiler used to configure CodeCheker. Also, CodeChecker doesn't seem to like `-isysroot` arguments in the command. Which is being set by the `CMAKE_OSX_SYSROOT` variable which we use. Might be also something to document, or counteract somehow.

But now it's seemingly running well now. We'll see at the end (tomorrow probably), it has to analyze about 750 TUs.

Thanks for the help so far guys!

**Comment by r0mai** [comment]
Success! It ran all the way only failing on one TU (which I know why) and it produced useful results. Awesome, thanks!

**Comment by gyorb** [comment]
I'm glad to hear it!

**Pull request merged**
