### PR TITLE
add new unknown options to the list

### PR DESCRIPTION
**Pull request by gyorb**
add new unknown option to the list unsupported by clang right now

### CODE REVIEW

**Comment by bruntib** [comment]
Wouldn't we like to cover the `no-` counterparts as well, like in case of `'^-m(no-)?spe.*': 0`?

**Comment by gyorb** [comment]
I'd like to keep this list as minimal as possible and only extend with elements which came up during analysis. I do not want to skip possible flags which could be handled by clang.
What specific flags do you have in mind?

**Comment by bruntib** [comment]
There are some duplicates in the list:
```
^-fno-var-tracking-assignments
^-fconserve-stack
^-fcond-mismatch
```
Some alphabetic or lexical ordering might help.

**Comment by gyorb** [comment]
thanks for pointing out the duplicates,

**Pull request merged**
