### PR TITLE
split up analyze and parse tests

### PR DESCRIPTION
**Pull request by gyorb**
splitting up the tests will allow to debug test failures easier

### CODE REVIEW

**Comment by Xazax-hun** [comment]
In case we need to do something slightly different for the different files I would prefer to have a special comment at the beginning of the test files rather than hardcoding everything in the code. What do you think?

**Comment by whisperity** [comment]
@Xazax-hun The tests files now already say how the analysis should run, akin to how Clang tests are structured. (It does not allow arbitrary execution however.)

**Comment by csordasmarton** [comment]
The following solution by using metaclass can solve this problem:
```py
class AnalyzeParseTestCaseMeta(type):
    def __new__(mcs, name, bases, dict):

        def gen_test(path, mode):
            def test(self):
                self.check_one_file(path, mode)
            return test

        test_dir = os.path.join(
            os.path.dirname(__file__), 'test_files')

        # Iterate over the test directory and run all tests in it.
        for ofile in glob.glob(os.path.join(test_dir, '*.output')):
            test_name = 'test_' + os.path.basename(ofile)
            dict[test_name + '_normal'] = gen_test(ofile, 'NORMAL')
            dict[test_name + '_check'] = gen_test(ofile, 'CHECK')

        return type.__new__(mcs, name, bases, dict)


class AnalyzeParseTestCase(unittest.TestCase):
    __metaclass__ = AnalyzeParseTestCaseMeta

    def check_one_file(self, path, mode):
        ...
```
What do you think @gyorb?

**Comment by gyorb** [comment]
@csordasmarton It looks good, I've updated the pull request. It still does not allow to skip specific tests with the `@unittest.skip` decorator but it will be easier to check the output of the tests.

**Pull request merged**
