### PR TITLE
[gui] Show report info in dialog at the report detail page

### PR DESCRIPTION
**Pull request by csordasmarton**
Screenshot:
image

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6282633&bid=20445018)

**Review by gyorb — CHANGES_REQUESTED** [review]
I do not think we should show the `run id` and `report id`. That data can not be used by the user they are just internal id's.
Otherwise LGTM.

**Comment by csordasmarton** [comment]
We use the report id in the URL's too, so I think this can be useful for the users too if we print it here.

And it can be also useful if you would like to search for a run or a report in your database (sqlite, psql). Maybe this one is only for maintainers but it's not hurt to anybody if we print these information too.

What do you think @bruntib?

**Comment by bruntib** [comment]
I think report hash might be useful in very rare cases if we want to check the hash algorithms, but that's rather for maintainers and not for users. Even if maintainers can see this hash in the reports view, I can accept that this hash is written on this page, because this is a property of the report. On the other hand I think nobody has ever searched or filtered reports by their hash, so if we want to simplify filter fields than this could be eliminated in my opinion, though this is off-topic for now :) For run ID I can't see any use case and it is not even the property of a report.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 57
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=6282633&bid=20445018)

**Comment by csordasmarton** [comment]
@bruntib Okay, I have removed the Run id field from the info but I would like to keep the report hash inside it for couple of reasons:
- we already show the the report hashes for each report on the Report list page.
- If the user clicks on the report hash on the report info dialog it will show him all the reports with the same hash.

By the way we can't say that nobody filtered on report hashes. It was a user requirement to show these report hashes and add an option to filter the reports based on these hashes. So I think it will not hurt to anybody if we show this hash in the report info dialog.
My opinion is that if we don't want to show the report hash in the report info dialog, we should remove it from the Report list page too.

**Review by gyorb — APPROVED** [review]

**Pull request merged**
