### PR TITLE
[report-converter] Sphinx parser

### PR DESCRIPTION
**Pull request by jay24rajput**
Sphinx report converter tool for parsing Sphinx output of kernel sources

### CODE REVIEW

**Comment by jay24rajput** [comment]
@bulwahn kindly have a look

**Review by csordasmarton — CHANGES_REQUESTED** [review]
One tiny comment otherwise LGTM!

**Comment by jay24rajput** [comment]
There you go @csordasmarton

**Review by csordasmarton — APPROVED** [review]
LGTM!

**Comment by csordasmarton** [comment]
@jay24rajput Thank you for your time that you implemented this :blush:

**Pull request merged**
