### PR TITLE
Refactoring log_parser to an external tool

### PR DESCRIPTION
**Pull request by bruntib**

### CODE REVIEW

**Comment by gyorb** [comment]
try out the converted compile command json with clang-tidy and clangd

**Comment by gyorb** [comment]
@bruntib the work in #2632 is the same you started here rigth?

**Comment by gamesh411** [comment]
> 
> 
> @bruntib the work in #2632 is the same you started here right?

It definitely seems that both PR-s are heading in the same direction.

**Comment by bruntib** [comment]
Log parser will be an external tool made by @gamesh411: #2632.

**Pull request closed without merging**
