### PR TITLE
feat(store): Explicitly time the client out if the connection hung

### PR DESCRIPTION
**Pull request by whisperity**
> Related to #3672, but does not implement it.

This is a partial solution that attempts to gracefully kill an ongoing `CodeChecker store` client if the reply to the `massStoreRun()` API call does not arrive in a timely manner. After reaching the timeout, the client throws an exception onto itself and presents an understandable error message about the situation. This implementation is temporary; thus, the timeout is a hard-coded limit.

The client still exits with a failure in these cases because there are no guarantees (and no deterministic ways to check) whether the timeout happened because the TCP connection failed and stuck (which is observed in a lot of cases, unfortunately) or whether the server indeed took more time than allotted to process the stored reports. A successful exit signal would result in CI scripts thinking the store was successful and then potentially breaking later, unreliably, on the fact that the stored run does not, in fact, exist or is in an outdated state, etc.

### CODE REVIEW

**Comment by whisperity** [comment]
## Example for the error message, as rendered to the terminal:

```
[INFO 2023-10-11 14:10] - Compressing report zip file...
[INFO 2023-10-11 14:10] - Compressing report zip file done (386EiB / 4TiB).
[INFO 2023-10-11 14:10] - Storing results to the server...
[WARNING 2023-10-11 14:10] - Timeout watchdog hit 3600 seconds (1:00:00)
Traceback (most recent call last):
  File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/cmd/store.py", line 872, in main
    client.massStoreRun(args.name,
  File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/thrift_call.py", line 45, in wrapper
    return func(*args, **kwargs)
  File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/codechecker_api/codeCheckerDBAccess_v6/codeCheckerDBAccess.py", line 2325, in massStoreRun
    self.send_massStoreRun(runName, tag, version, zipfile, force, trimPathPrefixes, description)
  File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/codechecker_api/codeCheckerDBAccess_v6/codeCheckerDBAccess.py", line 2340, in send_massStoreRun
    self._oprot.trans.flush()
  File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/thrift/transport/THttpClient.py", line 184, in flush
    self.__http_response = self.__http.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/cmd/store.py", line 760, in _signal_handler
    raise WatchdogError(timeout,
store.WatchdogError: Timeout watchdog hit 3600 seconds (1:00:00)
[ERROR 2023-10-11 14:10] - Timeout!
        The server's reply did not arrive after 3600 seconds (1:00:00) elapsed since the server-side processing began.

        This does *NOT* mean that there was an issue with the run you were storing!
        The server might still be processing the results...
        However, it is more likely that the server had already finished, but the client did not receive a response.
        Usually, this is caused by the underlying TCP connection failing to signal a low-level disconnect.
        Clients potentially hanging indefinitely in these scenarios is an unfortunate and known issue.
                See http://github.com/Ericsson/codechecker/issues/3672 for details!

        This error here is a temporary measure to ensure an infinite hang is replaced with a well-explained timeout.
        A more proper solution will be implemented in a subsequent version of CodeChecker.
```

**Comment by vodorok** [comment]
> ## Example for the error message, as rendered to the terminal:
> 
> ```
> [INFO 2023-10-11 14:10] - Compressing report zip file...
> [INFO 2023-10-11 14:10] - Compressing report zip file done (386EiB / 4TiB).
> [INFO 2023-10-11 14:10] - Storing results to the server...
> [WARNING 2023-10-11 14:10] - Timeout watchdog hit 3600 seconds (1:00:00)
> Traceback (most recent call last):
>   File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/cmd/store.py", line 872, in main
>     client.massStoreRun(args.name,
>   File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/thrift_call.py", line 45, in wrapper
>     return func(*args, **kwargs)
>   File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/codechecker_api/codeCheckerDBAccess_v6/codeCheckerDBAccess.py", line 2325, in massStoreRun
>     self.send_massStoreRun(runName, tag, version, zipfile, force, trimPathPrefixes, description)
>   File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/codechecker_api/codeCheckerDBAccess_v6/codeCheckerDBAccess.py", line 2340, in send_massStoreRun
>     self._oprot.trans.flush()
>   File "/home/whisperity/Ericsson/CodeChecker/venv_dev/lib/python3.10/site-packages/thrift/transport/THttpClient.py", line 184, in flush
>     self.__http_response = self.__http.getresponse()
>   File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
>     response.begin()
>   File "/usr/lib/python3.10/http/client.py", line 318, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.10/socket.py", line 705, in readinto
>     return self._sock.recv_into(b)
>   File "/home/whisperity/Ericsson/CodeChecker/build/CodeChecker/lib/python3/codechecker_client/cmd/store.py", line 760, in _signal_handler
>     raise WatchdogError(timeout,
> store.WatchdogError: Timeout watchdog hit 3600 seconds (1:00:00)
> [ERROR 2023-10-11 14:10] - Timeout!
>         The server's reply did not arrive after 3600 seconds (1:00:00) elapsed since the server-side processing began.
> 
>         This does *NOT* mean that there was an issue with the run you were storing!
>         The server might still be processing the results...
>         However, it is more likely that the server had already finished, but the client did not receive a response.
>         Usually, this is caused by the underlying TCP connection failing to signal a low-level disconnect.
>         Clients potentially hanging indefinitely in these scenarios is an unfortunate and known issue.
>                 See http://github.com/Ericsson/codechecker/issues/3672 for details!
> 
>         This error here is a temporary measure to ensure an infinite hang is replaced with a well-explained timeout.
>         A more proper solution will be implemented in a subsequent version of CodeChecker.
> ```

I would prefer if we would not show a stacktrace to the user. It is a "planned" exceptional behaviour, the error message is enough.

**Comment by whisperity** [comment]
> I would prefer if we would not show a stacktrace to the user. It is a "planned" exceptional behaviour, the error message is enough.

@vodorok I'm not sure about that. Without the stack trace, we do not know whether the timeout was triggered when **reading** from the socket (a.k.a., where we expect this) or during the **writing** of the socket (where such could, at least theoretically, also happen, but where we do NOT expect the program to hang for so long).

**Comment by vodorok** [comment]
I checked the implementation, and you only guard the rpc call with the watchdog.
In the end does the stacktracematter when the watchdog triggers and shoots down the store command?

**Review by dkrupp — APPROVED** [review]
The stack trace is a but ugly IMHO, but I understand why we need it.

LGTM.

**Comment by whisperity** [comment]
The only difference which *might* be meaningful is whether the send() fails versus the recv() failing. Nevertheless, I will put the stack trace behind the debug verbosity mode and update the patch.

**Comment by vodorok** [comment]
@whisperity  Thanks that is a good compromise.

**Comment by dkrupp** [comment]
I think it is much better like this. It is ok to be merged it.

**Pull request merged**
