### PR TITLE
View run count at the list of runs view

### LINKED ISSUE #1079: View run count on the list of runs view
View run count on the list of runs view

### PR DESCRIPTION
**Pull request by csordasmarton**
cc_run_count

Closes #1079

### CODE REVIEW

**Comment by whisperity** [comment]
Is this the current run count visible or all from the server? I recall Dojo lazily loading tables for some reason.

**Comment by whisperity** [comment]
Also, perhaps it could be put into the tab's title? Like on GitHub: 
image

But that would also require renaming the tab from "List of runs" to "Runs".

**Comment by csordasmarton** [comment]
@whisperity 
- The run count is the current run count (length of the `getRunData` function result).
- I moved the run count to the tab title. That was a great idea :+1: 
cc_run_count

**Comment by csordasmarton** [comment]
Done.
cc_run_count

**Pull request merged**
