### PR TITLE
Icons for detection status

### LINKED ISSUE #797: Icons for detection status
Once #724 has been merged, we should introduce some icons for the detection statuses instead of strings for the new filtering system.

### PR DESCRIPTION
**Pull request by csordasmarton**
Closes #797 

I made a screenshot from this feature:
cc_detection_status1

cc_detection_status_2

The meaning of icons:
- blue exclamation mark: new
- green tick: resolved
- red bug: unresolved
- grey loop arrow: reopened

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Could we have a tooltip to tell the user what the icon means when the mouse is over the icon?

**Comment by csordasmarton** [comment]
Yes, I added a tooltip for the icons:
cc_tooltip

**Comment by whisperity** [comment]
Considering that neither severity nor detection status now writes the actual value as string, and only uses an icon (with actual value in a tooltip), let's make _Review status_ have the same behaviour.

**Comment by csordasmarton** [comment]
Okay, I changed it.
I've also changed the `status` field (https://github.com/csordasmarton/codechecker/blob/version6/libcodechecker/orm_model.py#L256) type from Integer to `Enum` at the ReviewStatus orm Entity.

cc_sort

**Pull request merged**
