### PR TITLE
bump up version to 6.2.0

### PR DESCRIPTION
**Pull request by gyorb**

### CODE REVIEW

**Comment by csordasmarton** [comment]
Yes, you should increase the version string here:
https://github.com/Ericsson/codechecker/blob/64e128e075defb1e05002ecef481ca120d79fb84/www/scripts/version.js#L1

**Comment by gyorb** [comment]
@whisperity I prefer to do this in a pull request so we will not miss any configuration files with the version updates.
@whisperity and @csordasmarton why should I update the `CC_API_VERSION`? There was no api change this is just a new release with bug fixes and improvements. Only major and minor version is used there but these were not changed.

**Comment by csordasmarton** [comment]
Yes, you are right. You have to change this file if you make API changes.

**Comment by whisperity** [comment]
@gyorb Okay. Since I did the maintainer job on version upgrades a lot *more* files started to contain version-ish strings, and I forgot this when I wrote my previous comment.

Yes, API is versioned separately. It should remain 6.1, as of now.

**Pull request merged**
