### PR TITLE
Allow excluding web components from the build

### PR DESCRIPTION
**Pull request by jgalenson**
Building the web components requires extra dependencies such as npm.
To avoid requiring users that only require the command-line tool from
having to install these dependencies, we add a NO_WEB make variable to
exclude building web-related components.

### CODE REVIEW

**Comment by jgalenson** [comment]
I'm not very familiar with Make or this build system, so if I'm missing anything or there's an easier way to do this I'd be happy to hear about it.

**Comment by csordasmarton** [comment]
@jgalenson There are only two places in our Makefiles where we call npm:
https://github.com/Ericsson/codechecker/blob/c9f3b99aa3bc5c054a2048811edf5e42bdc3d975/web/Makefile#L55-L58
https://github.com/Ericsson/codechecker/blob/c9f3b99aa3bc5c054a2048811edf5e42bdc3d975/web/Makefile#L108-L111

In the first case you can skip this target if you create the dist directory: `mkdir -p web/server/vue-cli/dist`.
In the second case you have to run the `pip3 install -r ./requirements.txt` to make sure every pypi package is up-to-date. If the pypi packages are up-to-date then the npm install command will not be called.

So the following commands should skip npm calls:
```sh
mkdir -p web/server/vue-cli/dist
pip3 install -r ./requirements.txt

# Build CodeChecker.
make package
```

Maybe it would be useful for other users as well to introduce an environment variable to force skipping these targets. What do you think @gyorb?

**Comment by jgalenson** [comment]
Thanks!  That works for me (except that the second command should be `pip3 install -r web/requirements.txt` when run from the root of the repository).

With that, I have no need for this patch.  But it might still be useful to document this behavior or do something like this patch.

**Comment by gyorb** [comment]
@csordasmarton I think introducing an environment variable to skip building the web part would not hurt if someone wants to build a package only for analysis. (the plist to html tool does not use npm right now but it might cause problems again if we switch there to npm)

@jgalenson do you wanted to build only the analyzer part of the package, or some parts from the web too just without the web UI?
The  "server/cmd/store" sub commands are in the web part.

**Comment by jgalenson** [comment]
The analyzer is all we need at the moment.

**Comment by csordasmarton** [comment]
@jgalenson I created a patch (#3002) which is already merged and will solve this problem in an easy way.There is an environment variable now which can be used to skip building the UI code and calling npm: `BUILD_UI_DIST=NO make package`. What do you think?

**Comment by jgalenson** [comment]
That should work as well and is cleaner than the earlier commands.  Thanks!

**Comment by csordasmarton** [comment]
@jgalenson In this case if you don't mind I will close this PR.

**Pull request closed without merging**
