### PR TITLE
[report-converter] Write metada info into the plist files

### PR DESCRIPTION
**Pull request by csordasmarton**
Write the following metada information to the plist files created by the
`report-converter` tool:
- analyzer name
- name and version number of the tool which generated the plist files.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tools/report-converter/tests/unit/test_ubsan_parser.py  1
- tools/report-converter/tests/unit/test_spotbugs_parser.py  1
- tools/report-converter/tests/unit/test_infer_parser.py  4
- tools/report-converter/tests/unit/test_clang_tidy_parser.py  1
- tools/report-converter/tests/unit/test_cppcheck_parser.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5334634&bid=17462018)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tools/report-converter/tests/unit/test_spotbugs_parser.py  1
- tools/report-converter/tests/unit/test_cppcheck_parser.py  2
- tools/report-converter/tests/unit/test_clang_tidy_parser.py  1
- tools/report-converter/tests/unit/test_infer_parser.py  4
- tools/report-converter/tests/unit/test_ubsan_parser.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5334634&bid=17462018)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tools/report-converter/tests/unit/test_ubsan_parser.py  1
- tools/report-converter/tests/unit/test_clang_tidy_parser.py  1
- tools/report-converter/tests/unit/test_cppcheck_parser.py  2
- tools/report-converter/tests/unit/test_spotbugs_parser.py  1
- tools/report-converter/tests/unit/test_infer_parser.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5334634&bid=17462018)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tools/report-converter/tests/unit/test_golint_parser.py  1
- tools/report-converter/tests/unit/test_eslint_parser.py  1
- tools/report-converter/tests/unit/test_pylint_parser.py  1
- tools/report-converter/tests/unit/test_clang_tidy_parser.py  1
- tools/report-converter/tests/unit/test_cppcheck_parser.py  2
- tools/report-converter/tests/unit/test_pyflakes_parser.py  1
- tools/report-converter/tests/unit/test_spotbugs_parser.py  1
- tools/report-converter/tests/unit/test_tslint_parser.py  1
- tools/report-converter/tests/unit/test_infer_parser.py  4
- tools/report-converter/tests/unit/test_ubsan_parser.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5334634&bid=17462018)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- tools/report-converter/tests/unit/test_cppcheck_parser.py  2
- tools/report-converter/tests/unit/test_eslint_parser.py  1
- tools/report-converter/tests/unit/test_spotbugs_parser.py  1
- tools/report-converter/tests/unit/test_infer_parser.py  4
- tools/report-converter/tests/unit/test_golint_parser.py  1
- tools/report-converter/tests/unit/test_pylint_parser.py  1
- tools/report-converter/tests/unit/test_ubsan_parser.py  1
- tools/report-converter/tests/unit/test_pyflakes_parser.py  1
- tools/report-converter/tests/unit/test_clang_tidy_parser.py  1
- tools/report-converter/tests/unit/test_tslint_parser.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5334634&bid=17462018)

**Comment by csordasmarton** [comment]
@bruntib In case of Cppcheck we use our own hash only if the report hash is missing from the plist file or if it's `0`. Also in case of Cppcheck the `_post_process_result` function will get a `file_to_plist_data` dictionary  instead of a list of plist objects.

**Comment by csordasmarton** [comment]
Yes, cppcheck writes her own version under the `clang_version` key:
https://github.com/danmar/cppcheck/blob/08ddd847809d24988d35765574cfbdb49c178045/lib/errorlogger.cpp#L679-L680

For now we do not use these values but my plan is to show the tool name alongside the reports. These information are also good for us when a user reports a problem and send us his plist file.

**Comment by gyorb** [comment]
ok, just one more question for the other tools like infer the `clang_version` tag is used to store the version information too or it is different there?

**Comment by csordasmarton** [comment]
In case of infer the plist output will look like this: https://github.com/Ericsson/codechecker/blob/master/tools/report-converter/tests/unit/infer_output_test_files/dead_store.cpp.plist. So `clang_version` key is not set. As far as I see only cppcheck will use this key.

**Comment by gyorb** [comment]
ok, thanks for the clarification

**Pull request merged**
