### PR TITLE
[fix] Fix starting test docker containers

### LINKED ISSUE #1842: Docker container cannot be started
**Describe the bug**
Tried to build and run Docker container but it fails.

**CodeChecker version**
Latest commit `c55e32b`

**To Reproduce**
```
Baloghs-MacBook-Pro:codechecker tmsblgh$ docker build -t codechecker:test-sqlite-clang7-bionic --rm -f docker/Dockerfile.test.sqlite.clang7.bionic .
Sending build context to Docker daemon  25.96MB
Step 1/5 : FROM ubuntu:18.04
 ---> 1d9c17228a9e
Step 2/5 : RUN apt-get update   && apt-get install -y software-properties-common wget   && wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -   && add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main"   && apt-get update   && apt-get install --no-install-recommends -y        clang-7        clang-tidy-7        doxygen        libpq-dev        thrift-compiler        make        build-essential        curl        doxygen        gcc-multilib        git        python-virtualenv        python-dev        libsasl2-dev        libldap2-dev        libssl-dev   && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-7 100   && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-7 100   && update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-7 100
 ---> Using cache
 ---> 29a67cddc1be
Step 3/5 : COPY . /codechecker
 ---> 32405247e081
Step 4/5 : WORKDIR "/codechecker"
 ---> Running in 17c03b453465
Removing intermediate container 17c03b453465
 ---> 3cb5bef300d3
Step 5/5 : CMD ["make", "venv_dev", "pycodestyle", "package", "test_unit", "test_sqlite"]
 ---> Running in 73227ecba50a
Removing intermediate container 73227ecba50a
 ---> 0c5245e4e1e2
Successfully built 0c5245e4e1e2
Successfully tagged codechecker:test-sqlite-clang7-bionic
Baloghs-MacBook-Pro:codechecker tmsblgh$ 
Baloghs-MacBook-Pro:codechecker tmsblgh$ docker run --rm -ti codechecker:test-sqlite-clang7-bionic
# Create a virtual environment for development.
virtualenv -p python2 venv_dev && \
	. venv_dev/bin/activate && pip install -r requirements_py/dev/requirements.txt && \
	pip install -r requirements_py/test/requirements.txt
/bin/sh: 1: virtualenv: not found
Makefile:60: recipe for target 'venv_dev' failed
make: *** [venv_dev] Error 127
Baloghs-MacBook-Pro:codechecker tmsblgh$ 
```

**Expected behavior**
A running Docker container :)

**Desktop (please complete the following information)**
 - OS: macOS
 - Version: 10.14.2

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #1842

### CODE REVIEW

**Comment by csordasmarton** [comment]
@gyorb Done.

**Comment by bruntib** [comment]
When I run `sudo docker run --rm -ti codechecker:test-sqlite-clang7-bionic` I get this message:
`make: *** No rule to make target 'venv_dev'.  Stop.`
Am I doing something wrong?

**Comment by gyorb** [comment]
> When I run `sudo docker run --rm -ti codechecker:test-sqlite-clang7-bionic` I get this message:
> `make: *** No rule to make target 'venv_dev'. Stop.`
> Am I doing something wrong?

@bruntib I used the same command after building the image and I only got the clang version problem previously. Did you try to rebuild the image and execute the command again?

**Comment by csordasmarton** [comment]
@bruntib I tried it and I didn't get such an error. Please try to rebuild your docker image (maybe something is cached, you can use the `--no-cache` option of the docker build command to build without cache) and try to run the container again.

**Comment by bruntib** [comment]
It moved on, but I always have some error. Sometimes a timeout (of course this is not our fault), or sometimes a CodeChecker test fails (around database related functional tests). But basically the test running starts. I'll try running this image later as well unless somebody approves and merges it.

**Review by gyorb — DISMISSED** [review]
Please update the `docs/docker.md` with the docker filename changes.


It is interesting I get some errors during the test runs in the containers:
```
[HIGH] /codechecker/build/workspace/component-s5p8c7w_/test_proj/new_delete.cpp:37:3: Attempt to free released memory [cplusplus.NewDelete]              
[ERROR 2020-03-27 14:14] - Running check failed.                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                         
  File "/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/check.py", line 688, in main                                                          
    parse_module.main(parse_args)                                                                                                                                                          
  File "/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/cmd/parse.py", line 697, in main                                                                                   
    report_stats = rh.write(file_report_map)                                                                                                                                               
  File "/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/cmd/parse.py", line 199, in write                                                                                  
    source_file))                                                                                                                                                                     
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 46: ordinal not in range(128)                                                                                  
Traceback (most recent call last):                                                                                                                
  File "/codechecker/build/CodeChecker/cc_bin/../lib/python3/codechecker_analyzer/cmd/check.py", line 688, in main                                                                         
    parse_module.main(parse_args)                                                                                                                                   
  File "/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/cmd/parse.py", line 697, in main                                       
    report_stats = rh.write(file_report_map)                                                                                                                                                 File "/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/cmd/parse.py", line 199, in write                                          
    source_file))                                                                                                                                                                          
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 46: ordinal not in range(128)

```
Did the tests run successfully for you @csordasmarton ?

**Pull request merged**
