### PR TITLE
Skipfile normalization fix

### PR DESCRIPTION
**Pull request by Vodorok**
Skipfile normalization now occurs before skiplist handling.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=4875766&bid=16160723)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=4875766&bid=16160723)

**Comment by Vodorok** [comment]
Thanks @gyorb, extended the commit message.

**Comment by gyorb** [comment]
@Vodorok please create a PR for the v6.11.1 release branch too, Thanks!

**Pull request merged**
