### PR TITLE
[client] Do not store empty plist file to the server

### LINKED ISSUE #2659: "API call error: massStoreRun RequestFailed(errorCode=2" on storing the data
**Describe the bug**

Storing fails with 

```
[DEBUG][2020-03-30 20:08:30] {system} [104994] <140698457040704> - webserver_context.py:198 get_context() - Loading layout config.
[DEBUG][2020-03-30 20:08:30] {system} [104994] <140698457040704> - webserver_context.py:202 get_context() - /home/zzz/codechecker/build/CodeChecker/config/package_layout.json
[ERROR][2020-03-30 20:09:08] {system} [104994] <140698457040704> - thrift_call.py:54 wrapper() - API call error: massStoreRun
RequestFailed(errorCode=2, message="'/home/zzz/Documents/chromium/src/chrome/services/sharing/webrtc/p2p_socket_client_delegate.h'", extraInfo=None)
```

on 

`CodeChecker store ./ALL_REPORTS/ --name chrome --trim-path-prefix $(readlink -f $PWD/../../)  --verbose=debug  --url http://localhost:8000/Default
`

And no actual store is done.

**CodeChecker version**
```
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version                                 
---------------------------------------------------------------
Base package version | 6.12.0                                  
Package build date   | 2020-03-29T16:30                        
Git commit ID (hash) | 9e33f21258f67f6426dcd30cf426e9bdeb6187b1
Git tag information  | 6.12                                    
---------------------------------------------------------------

CodeChecker web version:
------------------------------------------------------------------------
Kind                          | Version                                 
------------------------------------------------------------------------
Base package version          | 6.12.0                                  
Package build date            | 2020-03-29T16:30                        
Git commit ID (hash)          | 9e33f21258f67f6426dcd30cf426e9bdeb6187b1
Git tag information           | 6.12                                    
Server supported API (Thrift) | 6.26                                    
Client API (Thrift)           | 6.26                                    
------------------------------------------------------------------------

```

**To Reproduce**

Run on Chromium sources:

`CodeChecker analyze ./chrome_compile_commands.json -j$(nproc) -i SKIP_FILE --timeout 600 -o $REPORT_DIR `

Well, $REPORT_DIR is 2Gb+ and there're about 20K files in it. But few month ago it was working fine.

**Expected behaviour**
Successful store.

**Desktop (please complete the following information)**
 - OS: Linux Ubuntu 19
 - Browser: any
 - Version: Linux ubuntu 5.3.0-42-generic #34-Ubuntu SMP Fri Feb 28 05:49:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
I tried to run the web-server both via docker and as a regular script in a console with the same result.

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #2659

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/client/codechecker_client/cmd/store.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5294899&bid=17331140)

**Comment by byterazor** [comment]
Hi,
this patch removed the error for me. In the webinterface the run is visible with the same number of defects than presented with CodeChecker parse.

Thank you very much !

**Comment by csordasmarton** [comment]
@gyorb You are right. I fixed it and I have also added a new test case which will check the storage of such plist files.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/client/codechecker_client/cmd/store.py  1
         

Clones removed
==============
+ web/tests/functional/skip/test_skip.py  -5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5294899&bid=17331140)

**Comment by csordasmarton** [comment]
@gyorb As you wrote the problem is that at here the reports are not parsed yet so it is not known which file should be stored or not.

Also I do not think we should handle this use case. This bug was introduced in the master branch and there is no such CodeChecker version which can produce such a plist file. With this patch this problem will be solved so in the new CodeChecker release it will work properly.

With this patch the content_hashes.json will not contain any extra files. If the diagnostics section is empty in a plist file then no source files will be added to the content_hashes.json file.

**Pull request merged**
