### PR TITLE
Add Python development headers to requirements

### PR DESCRIPTION
**Pull request by satbyy**
Otherwise, you'll get a compilation error about missing "Python.h"
when building one of the dependencies.

### CODE REVIEW

**Comment by gyorb** [comment]
Psycopg2 failed to build or some other dependecy?

**Comment by satbyy** [comment]
@gyorb I just changed README so not sure why the build failed. Is it possible to retrigger it somehow?

**Comment by gyorb** [comment]
I fixed travis #463 , please rebase your pull request.
On which linux did you run into the missing python-dev package problem?

**Comment by satbyy** [comment]
Ok, I rebased now. Seems Travis is happy. 'python-dev' was needed on Debian stable (jessie)

**Comment by gyorb** [comment]
Thanks!

**Pull request merged**
