### PR TITLE
Skip file analysing if any of skip_handlers returns True, not both.

### PR DESCRIPTION
**Pull request by irishrover**

### CODE REVIEW

**Comment by irishrover** [comment]
IMHO there's a typo in the current code.

**Comment by irishrover** [comment]
This patch dramatically reduces the amount of memory consumed and the processing time when 

> -i SKIP_FILE

is used.

**Comment by irishrover** [comment]
Gentle ping)

**Comment by irishrover** [comment]
> Do you use CTU for the analysis?

Mostly not. May be we can rewrite the condition as 

`if ... OR ctu_skip_handler_is_on AND (ctu_skip_handler and ctu_skip_handler.skip)`
?

Note `ctu_skip_handler_is_on`

**Comment by gyorb** [comment]
I've made a PR #2462 with some changes I'm thinking on but I did not test it yet properly.
It is a bit more change but makes the different skipping methods more explicit.

**Pull request closed without merging**
