### PR TITLE
increase current work in progress version to 5.9

### PR DESCRIPTION
**Pull request by gyorb**

### CODE REVIEW

**Comment by whisperity** [comment]
Starting the client with verbose mode will make `CodeChecker version` output a tainted git tag `v5.8.0-123-g1234567` showing that the current build was created with changes above `5.8.0`.

Doesn't introducing this change create a confusion, as in this state, `5.9.0` is used for all version strings, including the verbose "taint" string too?

**Comment by gyorb** [comment]
With this release we will change when the version is updated. 
In the current case we released v5.8 and we are working on v5.9 the version info will reflect that. Until v5.9 is not released we assume this is not a stable release.
If the users build a package from the master branch it will indicate that this version is ahead of the latest released version.
I do not think it will be too much confusing. The taint tag will show what is the latest commit and v5.9 will show that this is the version we are working now.

**Comment by whisperity** [comment]
Actually, upon further thinking into it, the taint tag will still show `v5.8.0-NUMBER-gSHA`, because the latest git tag available in the repository is still `v5.8`. 🙂

**Comment by gyorb** [comment]
Ok, than this needs to be changed later. So not the latest git tag is used as the version.

**Comment by whisperity** [comment]
It only shows in `--verbose debug` mode. In "normal" modes, the API-given version is used.

**Comment by gyorb** [comment]
I've created a separate issue to change the printed version so it will be consistent everywhere.

**Pull request merged**
