### PR TITLE
[web] Add description for each run

### LINKED ISSUE #2542: add description for each run
Add support to store description for each run.
It can be a free text so the user can store any analysis related information there.

```sh
 CodeChecker store ./report_directory -n myproject  --description “analysis related extra information”
```
The stored data could be visible on the UI at the run history view.

### PR DESCRIPTION
**Pull request by csordasmarton**
> Closes #2542

Add support to store description for each run. It can be a free text so
the user can store any analysis related information there.

Example:
```sh
CodeChecker store ./report_dir -n myproject --description "analysis related extra information"
```

The stored description will be visible on the UI at the run history and
run list views.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/tests/libtest/codechecker.py  1
- web/server/codechecker_server/migrations/report/versions/5f8a443a51e5_add_description_for_run_history.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5333393&bid=17456862)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/tests/libtest/codechecker.py  1
- web/server/codechecker_server/migrations/report/versions/5f8a443a51e5_add_description_for_run_history.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5333393&bid=17456862)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/server/codechecker_server/migrations/report/versions/5f8a443a51e5_add_description_for_run_history.py  1
- web/tests/libtest/codechecker.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5333393&bid=17456862)

**Comment by csordasmarton** [comment]
@gyorb Did you remove the `web/server/vendor/codechecker-api-js/` directory before you created the package?

**Comment by gyorb** [comment]
I've made the package with `make clean` and `make package` that should clean every older js file right?

**Comment by csordasmarton** [comment]
@gyorb Sorry, your problem is related to python. Did you refresh your venv: `make clean_venv_dev && make venv_dev`

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/tests/libtest/codechecker.py  1
- web/server/codechecker_server/migrations/report/versions/5f8a443a51e5_add_description_for_run_history.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5333393&bid=17456862)

**Comment by csordasmarton** [comment]
@gyorb It's weird. I tried it in _Chrome_ (Version 80.0.3987.149 (Official Build) (64-bit)) and _Firefox_ (69.0.1 (64-bit)) and it works for me:
run_description.

- Could you please check that your browser downloaded the correct javascript files:
  - Open the developer console (F12)
  - In Firefox go to the Debugger tab / in chrome to the Sources tab
  - Find the `ListOfRuns.js` file and check that my modification can be found in your file (for example the keyword `description`.
- Do you see any error in your console?
- Could you please try it in private mode in case of both browsers: Chromium and Firefox.

**Comment by gyorb** [comment]
> @gyorb It's weird. I tried it in _Chrome_ (Version 80.0.3987.149 (Official Build) (64-bit)) and _Firefox_ (69.0.1 (64-bit)) and it works for me:
> 
> * Could you please check that your browser downloaded the correct javascript files:
>   
>   * Open the developer console (F12)
>   * In Firefox go to the Debugger tab / in chrome to the Sources tab
>   * Find the `ListOfRuns.js` file and check that my modification can be found in your file (for example the keyword `description`.

Yes, I found source code mentioning description.

> * Do you see any error in your console?

No, just some warnings
[Deprecation] Synchronous XMLHttpRequest on the main ...
DevTools failed to load SourceMap: 

> * Could you please try it in private mode in case of both browsers: Chromium and Firefox.

Tried in both the results are the same.
See the picture below.

run-deescription

**Comment by gyorb** [comment]
I managed to make it work after multiple environment cleanups.

**Pull request merged**
