### PR TITLE
[analyzer] Support compile_command.jsons with relative paths to compilers.

### PR DESCRIPTION
**Pull request by Xazax-hun**
I encountered a build system where some of the compilers have relative paths in the compile commands. That should work well with CodeChecker after this patch. Unfortunately, I have no time to add tests at the moment. Feel free to commandeer this patch.

### CODE REVIEW

**Comment by Xazax-hun** [comment]
Whenever we convert a relative path to absolute we lose some information and do get less fidelity compared to the original build. We could do that but I wonder if it will bite us later on. Historically, we reverted changes that made paths absolute. 


For example as soon as the compiler path is made absolute, which working directory should we use? Are all of them the same in the compilation database? Not necessarily.

**Comment by Xazax-hun** [comment]
Also, note that we even if we convert the path to absolute, we still need a correct working directory. The working directory can change how the compiler resolves some includes etc.

**Comment by gamesh411** [comment]
I have an insidious idea. Maybe the correct way of handling paths would be to use the absolute, however, if we create an absolute path out of a relative, we could encode it as a double slash at the point of conversion (ie dir: /a/b, file:c -> /a/b//c). As far as I know, consecutive slashes are ignored (I also checked the POSIX standard, but there is no mention of consecutive slashes in the middle of a path). This would be extremely brittle. This could break with any path normalization. Also, there is no guarantee that every path-resolution environment handles this.

**Comment by Xazax-hun** [comment]
Still, regardless of the conversion, not setting the working directory correctly is likely to introduce problems.

**Comment by Xazax-hun** [comment]
Is there still any concerns regarding this fix? I think making the path absolute is not a correct solution as the headers found by the compiler depends on the working directory. We should never execute a compiler with the wrong working directory.

**Comment by Xazax-hun** [comment]
It looks like some recent changes made the current situation worse:
https://github.com/Ericsson/codechecker/blob/master/analyzer/codechecker_analyzer/buildlog/log_parser.py#L978

Here we also call `get_clangsa_version_func` without passing the correct working directory. I think we should always set the correct working directory when we call into the compiler. 

Also, why do we invoke `get_clangsa_version_func`? The user might not even run `clangsa`, only `clang-tidy`. I think we should not have `clangsa` related functionality in a general utility that is used by other analyzers.

**Comment by gyorb** [comment]
`get_clangsa_version_func` will not be called on clang-tidy it will be called on the compiler in the compile command database. If we manage to parse a valid clang version we assume it is a clang compiler and less compilation argument filtering is done.
If `get_clangsa_version_func` failed to parse a valid clang version it will return false and we assume it is not a clang compiler.
We need this because we run into build systems and environments where clang is symlinked to gcc or gcc is symlinked to clang. We can not depend only on the name to find out if it is gcc or clang.

But if the compiler cwd influences the implicit include paths it might not be enough to use the compiler as a key in `ICI.compiler_info[compiler]` when we collect the information and later when it is used.
The exported compiler info json needs to be extended with the cwd information as well.

**Comment by Xazax-hun** [comment]
> `get_clangsa_version_func` will not be called on clang-tidy it will be called on the compiler in the compile command database. If we manage to parse a valid clang version we assume it is a clang compiler and less compilation argument filtering is done.

For me it sounds like the name of the function needs to be changed.

**Comment by gyorb** [comment]
Ok, we can think of a better name for that variable if you want, but it is documented what type function is expected to be passed to the `parse_options` function.
```
    get_clangsa_version_func -- Is a function which should return the
                            version information for a clang compiler.
                            It requires the compiler binary and an env.
                            get_clangsa_version_func(compiler_binary, env)
                            Should return false for a non clang compiler.
```
Renaming it will still not solve the mentioned problems.

**Comment by csordasmarton** [comment]
Closing this pull request as there have been no activity on it in a long time.

**Pull request closed without merging**
