### PR TITLE
[gui] Keepalive component states

### PR DESCRIPTION
**Pull request by csordasmarton**
Use vue `keep-alive` built-in component to cache component states.

So for example when navigating from the Runs page to the Reports page
the state of the Runs page component is saved. So once we go back to the
Runs page component the user will see the previous state.

This will also help us to reduce API requests to the server.

### CODE REVIEW

**Comment by bruntib** [comment]
If I apply some filters in "reports" view and navigate among pages, then the filter options are preserved, so it works properly. However, if I apply some filters on "reports" page and jump to "statistics" then these filter options are not ported there. Is this the expected behavior?

**Comment by csordasmarton** [comment]
@bruntib Yes, for now this is the expected behaviour because the reports page and the statistics page have separate filter objects.

**Review by gyorb — APPROVED** [review]

**Comment by gyorb** [comment]
filters will be kept between the "reports" page and "statistics" page when the same filter will be available on both pages right @csordasmarton? That will be the next step.

**Comment by csordasmarton** [comment]
@gyorb Yes, as you said, it will be the next step.

**Pull request merged**
