### PR TITLE
Increase Firefox supported version to 22.0

### LINKED ISSUE #1084: show the supported browser version
After the server was started and I try to view the results in an unsupported browser I got only a blank page.
It would be better to show the supported and unsupported browser versions.

### PR DESCRIPTION
**Pull request by csordasmarton**
The latest supported Firefox version is 22.0 (https://ftp.mozilla.org/pub/firefox/releases/22.0/linux-x86_64/en-US/). I have increased the supported browser version to this.

Closes #1084

### CODE REVIEW

**Comment by bruntib** [comment]
Wouldn't it be worth factoring this version checking code and information message to an external .js file for avoiding code duplication? That could be included by a `<script>` tag.

**Comment by gyorb** [comment]
For which javascript library is this the minimal required version?

**Comment by csordasmarton** [comment]
@bruntib I moved the compatible code to an external .js file.
@gyorb I replaced some non compatible feature to support older browsers (**Firefox >=22.0**). What is the minimal version which we would like to support? Now older browsers (<22.0) are throwing errors on Array filter function (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter).

**Comment by gyorb** [comment]
I think 22.0 and above should be fine but please check if the unsupported message is shown properly in older browsers mentioned by @dkrupp in the issue.

**Comment by csordasmarton** [comment]
@gyorb I tested it with Firefox 17.0 and 22.0 (https://ftp.mozilla.org/pub/firefox/releases/17.0/linux-x86_64/en-US/) and the non compatible version messages was shown properly.

**Pull request merged**
