### PR TITLE
Example CI script for comparing master changes and pull request runs

### LINKED ISSUE #994: create a bash script template for incremental analysis jenkins job
Create a template bash script which emulates the email sending
Extend the usage doc with the template:
https://github.com/Ericsson/codechecker/blob/master/docs/usage.md#storing-the-results-of-each-commit-and-guarding-the-introduction-of-new-bugs

### PR DESCRIPTION
**Pull request by whisperity**
Closes #994.

### CODE REVIEW

**Comment by whisperity** [comment]
@gyorb There is a subsection titled _Storing the results of each commit and guarding the introduction of new bugs_. This exactly described the use-case where there is a master server which already contains a trunk/master/upstream bug database, and the pull request is analyzed *against* it.

**Comment by gyorb** [comment]
@whisperity thanks, I've missed that

**Comment by whisperity** [comment]
It's better if the branch gets rebased instead of merge commits being pushed into it.

**Comment by gyorb** [comment]
@whisperity Yes, I know I've just wanted to try out the new resolve merge conflict on the GitHub webpage and it resolves it this way. I was not sure you will have time to fix the merge conflict.
You can rebase it and clean it up.

**Pull request merged**
