### PR TITLE
[report-converter] Skip incorrect CppCheck Plist files

### LINKED ISSUE #2571: Report converter crashes when converting corrupted cppcheck results
**Describe the bug**
After analyzing LLVM on the `llvmorg-9.0.0` tag with CppCheck on commit e9b7e7811be942b5ffe20d424baf0e2db30355bd with the following command:
```bash
$ cppcheck --enable=all --project=compile_commands.json --plist-output=results/cppcheck_pre -j12
```
converting fails:
```bash
$ report-converter --type cppcheck results/cppcheck_pre/AssemblerTest.plist -o results/cppcheck_results -v
Traceback (most recent call last):
  File "codechecker/tools/report-converter/venv/bin/report-converter", line 11, in <module>
    load_entry_point('report-converter', 'console_scripts', 'report-converter')()
  File "codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 123, in main
    args.clean)       
  File "codechecker/tools/report-converter/codechecker_report_converter/cli.py", line 64, in output_to_plist
    parser.transform(analyzer_result, output_dir)
  File "codechecker/tools/report-converter/codechecker_report_converter/analyzer_result.py", line 35, in transform
    plist_objs = self.parse(analyzer_result)
  File "codechecker/tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py", line 51, in parse
    file_to_plist_data[file_name] = plistlib.readPlist(f)
  File "/usr/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)                          
  File "/usr/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)       
xml.parsers.expat.ExpatError: junk after document element: line 364, column 8
 ```

Its worth noting that the plist file is incorrect -- I suspect running multiple jobs messes with CppCheck.

**CodeChecker version**
The report converter was built on commit 7cbfce477ccbfc0c2f0df59aacc031ba8a451d6d.

**Expected behavior**
Emit a proper error message about the incorrect file.

**Desktop (please complete the following information)**
 - OS: Ubuntu 18.04

**Additional context**
I generated the plist file on a server, but I could reproduce the crash by simply copying said plist file and trying to convert locally, so I attached it:
[AssemblerTest.zip](https://github.com/Ericsson/codechecker/files/4204754/AssemblerTest.zip)

### PR DESCRIPTION
**Pull request by Szelethus**
Closes #2571.

I'm publishing this as a sign that I managed to find a satisfying solution to the issue raised, but I didn't have the time to write tests just yet. I'll revise this PR later.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5039601&bid=16597465)

**Comment by Szelethus** [comment]
> What was the problem with the plist file? The file location was invalid and the hash could not be generated?

CppCheck (especially when ran with multiple jobs) is prone to mess up the plist files. The cases I encountered were either
1. Referencing a file number that is greater then the amount of files specified
2. The plist file was a tangled up unparseable mess.
Further reading and examples can be found in #2571.

**Comment by gyorb** [comment]
@Szelethus could you resolve the conflicts?

**Comment by Szelethus** [comment]
I'm a bit sidetracked on other projects, but I'll try to finish this up tomorrow. Sorry for the slack!

**Review by csordasmarton — APPROVED** [review]
@Szelethus I updated/rebased your patch because I want to merge this.

**Pull request merged**
