### PR TITLE
fix pylint unused-wildcard-import warnings #2082

### LINKED ISSUE #2082: fix pylint unused-wildcard-import warnings
W0614 - Warns when an imported module or variable is not used from a 'from X import *' style import.

Only import what is used.

### PR DESCRIPTION
**Pull request by meghajain-1711**
W0614 - Warns when an imported module or variable is not used from a 'from X import *' style import.
Only import what is used.

Currently the codebase didnot have any specific such imports. Still pylintrc have been updated to report unused-wildcard-imports

resolves #2082

### CODE REVIEW

**Review by gyorb — COMMENTED** [review]
There is a small typo (a missing space) in the commit message otherwise LGTM.
`Currently the codebase didnot have ...` -> `Currently the codebase did not have ...`

**Comment by meghajain-1711** [comment]
> There is a small typo (a missing space) in the commit message otherwise LGTM.
> `Currently the codebase didnot have ...` -> `Currently the codebase did not have ...`

Thanks for the feedback @gyorb . My bad !  What would you suggest , should I re-do PR or do a manual change, amend, and force push ?

**Comment by csordasmarton** [comment]
@meghajain-1711 You can just amend your commit and force push it.

```sh
git commit --amend
git push -f
```

**Comment by meghajain-1711** [comment]
> @meghajain-1711 You can just amend your commit and force push it.
> 
> ```shell
> git commit --amend
> git push -f
> ```

Thanks a lot for the confirmation @csordasmarton ! Updated :)

**Review by csordasmarton — APPROVED** [review]
Thank you for your contribution :blush:. It's LGTM!

**Pull request merged**
