### PR TITLE
[cmd] Show available env vars in cmd help

### PR DESCRIPTION
**Pull request by csordasmarton**
Show available environment variables in the command line help.

### CODE REVIEW

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- web/codechecker_web/shared/arg.py  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5354610&bid=17543089)

**Comment by csordasmarton** [comment]
@bruntib I refactored the code. Now there will be only one argparse formatter.

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- codechecker_common/arg.py  5
         

Complexity decreasing per file
==============================
+ analyzer/codechecker_analyzer/arg.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5354610&bid=17543089)

**Comment by gyorb** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- codechecker_common/arg.py  5
         

Complexity decreasing per file
==============================
+ analyzer/codechecker_analyzer/arg.py  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/CodeChecker/codechecker/pullRequest?prid=5354610&bid=17543089)

**Pull request merged**
